// Generated by CoffeeScript 1.4.0
(function() {
  var http;

  http = require('http');

  http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content Type': 'text/plain'
    });
    res.writeBody('Hello World\n');
  }).listen(process.env.coffee, process.env.IP);

}).call(this);
